name: voyarr-dev
services:
  backend:
    build:
      context: ./backend
  celery_worker:
    build:
      context: ./backend
  celery_beat:
    build:
      context: ./backend
  frontend:
    build:
      context: ./frontend
