name = "voyarr"
main = "src/index.js"
compatibility_date = "2024-12-01"

assets = { directory = "../frontend/dist", binding = "ASSETS" }

routes = [{ pattern = "voyarr.gabrieljustinsider.com/*", zone_id = "a7bbfed2974f3d8579f7d3aaceeb8598" }]

[observability]
enabled = true
