name: Add to GitHub Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Load secrets from 1Password
        id: op-secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PROJECT_PAT: "op://6wgu5yz5yphvacdimgc64ej65i/Voyarr - GitHub Project PAT/token"

      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/users/gabrieljustinsider/projects/1
          github-token: ${{ env.PROJECT_PAT }}
